"""empty message

Revision ID: 9c45d02338ed
Revises: 
Create Date: 2020-04-13 22:39:08.008522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c45d02338ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('number_of_copies', sa.Integer(), nullable=True, default=1))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'number_of_copies')
    # ### end Alembic commands ###
